Repository galaxyproject/usegalaxy-tools, pull requests merged in 2019-09, with the labels that each got.

#49 Fix incorrect YAML in compose_text_param.yml
  usegalaxy.org/compose_text_param.yml
Labels: bug

#51 Install in Jenkins
  .ci/jenkins.sh
  .ci/repos.conf
Labels: meta

#52 Allow for the use of `tool_shed_url` in tool YAMLs
  .schema.yml
  scripts/fix-lockfile.py
  scripts/update-tool.py
Labels: meta

#54 Install dynamic downsampling tool on test.
  .ci/jenkins.sh
  .ci/tool_sheds_conf.xml
  test.galaxyproject.org/dynamic_downsample.yml
  test.galaxyproject.org/dynamic_downsample.yml.lock
Labels: site/org/test, tools/new
